import type { SimpleSelectOption } from "@simply-patternfly/core";

export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const statesWithKey: SimpleSelectOption[] = [
  { key: "AL", value: "Alabama" },
  { key: "AK", value: "Alaska" },
  { key: "AZ", value: "Arizona" },
  { key: "AR", value: "Arkansas" },
  { key: "CA", value: "California" },
  { key: "CO", value: "Colorado" },
  { key: "CT", value: "Connecticut" },
  { key: "DE", value: "Delaware" },
  { key: "FL", value: "Florida" },
  { key: "GA", value: "Georgia" },
  { key: "HI", value: "Hawaii" },
  { key: "ID", value: "Idaho" },
  { key: "IL", value: "Illinois" },
  { key: "IN", value: "Indiana" },
  { key: "IA", value: "Iowa" },
  { key: "KS", value: "Kansas" },
  { key: "KY", value: "Kentucky" },
  { key: "LA", value: "Louisiana" },
  { key: "ME", value: "Maine" },
  { key: "MD", value: "Maryland" },
  { key: "MA", value: "Massachusetts" },
  { key: "MI", value: "Michigan" },
  { key: "MN", value: "Minnesota" },
  { key: "MS", value: "Mississippi" },
  { key: "MO", value: "Missouri" },
  { key: "MT", value: "Montana" },
  { key: "NE", value: "Nebraska" },
  { key: "NV", value: "Nevada" },
  { key: "NH", value: "New Hampshire" },
  { key: "NJ", value: "New Jersey" },
  { key: "NM", value: "New Mexico" },
  { key: "NY", value: "New York" },
  { key: "NC", value: "North Carolina" },
  { key: "ND", value: "North Dakota" },
  { key: "OH", value: "Ohio" },
  { key: "OK", value: "Oklahoma" },
  { key: "OR", value: "Oregon" },
  { key: "PA", value: "Pennsylvania" },
  { key: "RI", value: "Rhode Island" },
  { key: "SC", value: "South Carolina" },
  { key: "SD", value: "South Dakota" },
  { key: "TN", value: "Tennessee" },
  { key: "TX", value: "Texas" },
  { key: "UT", value: "Utah" },
  { key: "VT", value: "Vermont" },
  { key: "VA", value: "Virginia" },
  { key: "WA", value: "Washington" },
  { key: "WV", value: "West Virginia" },
  { key: "WI", value: "Wisconsin" },
  { key: "WY", value: "Wyoming" },
];

export const countries = [
  { key: "AE", value: "United Arab Emirates" },
  { key: "AL", value: "Albania" },
  { key: "AR", value: "Argentina" },
  { key: "AU", value: "Australia" },
  { key: "BA", value: "Bosnia and Herzegovina" },
  { key: "BE", value: "Belgium" },
  { key: "BG", value: "Bulgaria" },
  { key: "BR", value: "Brazil" },
  { key: "BY", value: "Belarus" },
  { key: "CA", value: "Canada" },
  { key: "CL", value: "Chile" },
  { key: "CN", value: "China" },
  { key: "CO", value: "Colombia" },
  { key: "CZ", value: "Czech Republic" },
  { key: "DE", value: "Germany" },
  { key: "DK", value: "Denmark" },
  { key: "EG", value: "Egypt" },
  { key: "ES", value: "Spain" },
  { key: "FR", value: "France" },
  { key: "GR", value: "Greece" },
  { key: "HR", value: "Croatia" },
  { key: "HU", value: "Hungary" },
  { key: "IN", value: "India" },
  { key: "IT", value: "Italy" },
  { key: "JP", value: "Japan" },
  { key: "KR", value: "South Korea" },
  { key: "MD", value: "Moldova" },
  { key: "ME", value: "Montenegro" },
  { key: "MK", value: "North Macedonia" },
  { key: "MX", value: "Mexico" },
  { key: "NL", value: "Netherlands" },
  { key: "NO", value: "Norway" },
  { key: "NZ", value: "New Zealand" },
  { key: "PE", value: "Peru" },
  { key: "PL", value: "Poland" },
  { key: "RO", value: "Romania" },
  { key: "RS", value: "Serbia" },
  { key: "RU", value: "Russia" },
  { key: "SA", value: "Saudi Arabia" },
  { key: "SE", value: "Sweden" },
  { key: "SI", value: "Slovenia" },
  { key: "SK", value: "Slovakia" },
  { key: "UA", value: "Ukraine" },
  { key: "UK", value: "United Kingdom" },
  { key: "US", value: "United States" },
  { key: "VE", value: "Venezuela" },
  { key: "ZA", value: "South Africa" },
];

export type User = {
  id: number;
  name: string;
  age: number;
  email: string;
};

export const tableData = [
  { id: 1, name: "John Doe", age: 30, email: "john.doe@example.com" },
  { id: 2, name: "Jane Doe", age: 25, email: "jane.doe@example.com" },
  { id: 3, name: "Jim Doe", age: 20, email: "jim.doe@example.com" },
  { id: 4, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 5, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
  { id: 6, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 7, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
  { id: 8, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 9, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
  { id: 10, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 11, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
  { id: 12, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 13, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
  { id: 14, name: "Jill Doe", age: 22, email: "jill.doe@example.com" },
  { id: 15, name: "Jack Doe", age: 23, email: "jack.doe@example.com" },
];